name: websimple
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://panuska.net
#author: Petr Panuska <pe-pan@centrum.cz>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.7.4
  build_daemon: ^2.1.3
  build_web_compilers: ^2.9.0
  pedantic: ^1.9.0

  mailer: ^3.0.4
  twitter: ^1.0.0
  http: ^0.11.2
  postgres: ^2.1.0
  shortid: ^0.1.1
  logger: ^0.8.3